### PR TITLE
link docker to podman

### PR DESCRIPTION
**Pull request by nekator**
gh-19 fix

### CODE REVIEW

**Comment by yahavi** [comment]
recheck

**Comment by yahavi** [comment]
recheck

**Comment by yahavi** [comment]
recheckcla

**Comment by nekator** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by nekator** [comment]
created a [feature request](https://github.com/jfrog/jfrog-cli/issues/1472) in jfrog-cli to implement missing podman command instead of this workaround

**Pull request closed without merging**
